Legacy-Fabric/yarn

- mappings/net/minecraft/client/gui/screen/Screen.mapping
> Changed method_2802 to shouldPauseGame() in Screen.class

- mappings/net/minecraft/class_715.mapping
- mappings/net/minecraft/client/MinecraftClient.mapping
- mappings/net/minecraft/client/entity/VillageParticle.mapping
- mappings/net/minecraft/client/gui/hud/InGameHud.mapping
- mappings/net/minecraft/client/gui/hud/OverlayDebug.mapping
- mappings/net/minecraft/client/gui/hud/StreamIndicatorHud.mapping
- mappings/net/minecraft/client/model/ModelPart.mapping
- mappings/net/minecraft/client/particle/BlockDustParticle.mapping
- mappings/net/minecraft/client/particle/BlockLeakParticle.mapping
- mappings/net/minecraft/client/particle/BlockParticle.mapping
- mappings/net/minecraft/client/particle/CloudParticle.mapping
- mappings/net/minecraft/client/particle/DamageParticle.mapping
- mappings/net/minecraft/client/particle/EmotionParticle.mapping
- mappings/net/minecraft/client/particle/EnchantGlyphParticle.mapping
- mappings/net/minecraft/client/particle/ExplosionSmokeParticle.mapping
- mappings/net/minecraft/client/particle/FireSmokeParticle.mapping
- mappings/net/minecraft/client/particle/FireworksSparkParticle.mapping
- mappings/net/minecraft/client/particle/FootstepParticle.mapping
- mappings/net/minecraft/client/particle/LargeExplosionParticle.mapping
- mappings/net/minecraft/client/particle/ParticleFactory.mapping
- mappings/net/minecraft/client/particle/PortalParticle.mapping
- mappings/net/minecraft/client/particle/RainSplashParticle.mapping
- mappings/net/minecraft/client/particle/RedstoneParticle.mapping
- mappings/net/minecraft/client/particle/SnowShovelParticle.mapping
- mappings/net/minecraft/client/particle/SnowballParticle.mapping
- mappings/net/minecraft/client/particle/SpellParticle.mapping
- mappings/net/minecraft/client/particle/SuspendedParticle.mapping
- mappings/net/minecraft/client/particle/WaterBubbleParticle.mapping
- mappings/net/minecraft/client/particle/WaterSplashParticle.mapping
- yarn.bat
Mapped all particle factories and particle classes.
Closes #21 
Closes #22 
Closes #23 
Closes #24 
```kotlin
Changes to be committed:
deleted:    yarn.bat
deleted:    mappings/net/minecraft/class_715.mapping
modified:   mappings/net/minecraft/client/MinecraftClient.mapping
modified:   mappings/net/minecraft/client/gui/hud/InGameHud.mapping
new file:   mappings/net/minecraft/client/gui/hud/OverlayDebug.mapping
new file:   mappings/net/minecraft/client/gui/hud/StreamIndicatorHud.mapping
modified:   mappings/net/minecraft/client/model/ModelPart.mapping
new file:   mappings/net/minecraft/client/entity/VillageParticle.mapping
modified:   mappings/net/minecraft/client/particle/BlockDustParticle.mapping
modified:   mappings/net/minecraft/client/particle/BlockLeakParticle.mapping
new file: …
```
> Particles and other client side stuff

- mappings/com/mojang/blaze3d/platform/GlHelper.mapping
- mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
- mappings/net/minecraft/block/Blocks.mapping
- mappings/net/minecraft/class_1355.mapping
- mappings/net/minecraft/world/level/LevelProperties.mapping
Mapped all(lots if not all) methods and fields in GlStateManager, and wrote Javadoc for them. Also fixes a critical bug (*which I might have introduced*).
Closes #42 
Closes #43
> Mappings and Javadoc for GlStateManager

- mappings/com/mojang/blaze3d/platform/AdvancedOpenGlManager.mapping
- mappings/net/minecraft/class_1039.mapping
- mappings/net/minecraft/effect/StatusEffectStrings.mapping
- mappings/net/minecraft/entity/EntityType.mapping
- mappings/net/minecraft/entity/LivingEntity.mapping
- mappings/net/minecraft/item/AppleItem.mapping
- mappings/net/minecraft/item/FishItem.mapping
- mappings/net/minecraft/item/FoodItem.mapping
- mappings/net/minecraft/item/GoldenAppleItem.mapping
- mappings/net/minecraft/item/Item.mapping
- mappings/net/minecraft/item/ItemFrameItem.mapping
- mappings/net/minecraft/item/MinecartItem.mapping
- mappings/net/minecraft/item/MushroomStewItem.mapping
- mappings/net/minecraft/item/PotionItem.mapping
- mappings/net/minecraft/item/ShovelItem.mapping
- mappings/net/minecraft/item/SkullItem.mapping
- mappings/net/minecraft/item/SplashPotionItem.mapping
- mappings/net/minecraft/item/StewItem.mapping
- mappings/net/minecraft/item/SwordItem.mapping
Changelog:-
```toml
On branch dev2
Changes to be committed:
new file:   mappings/net/minecraft/class_1039.mapping
modified:   mappings/net/minecraft/effect/StatusEffectStrings.mapping
modified:   mappings/net/minecraft/entity/EntityType.mapping
modified:   mappings/net/minecraft/entity/LivingEntity.mapping
modified:   mappings/net/minecraft/item/AppleItem.mapping
modified:   mappings/net/minecraft/item/FishItem.mapping
new file:   mappings/net/minecraft/item/FoodItem.mapping
deleted:    mappings/net/minecraft/item/GoldenAppleItem.mapping
modified:   mappings/net/minecraft/item/Item.mapping
modified:   mappings/net/minecraft/item/ItemFrameItem.mapping
modified:   mappings/net/minecraft/item/MinecartItem.mapping
deleted:    mappings/net/minecraft/item/MushroomStewItem.mapping
modified: …
```
> Item classes and more Advanced Open Gl

- mappings/net/minecraft/server/world/ServerWorld.mapping
- mappings/net/minecraft/world/DemoServerWorld.mapping
- mappings/net/minecraft/world/DemoWorld.mapping
- mappings/net/minecraft/world/GameRules.mapping
```diff
+ net.minecraft.world.DemoServerWorld
+ net.minecraft.world.GameRules
+ MinecraftServer Arguments (arg4, arg5 -> properties, dimensionType)
+ Other stuff (idk)
```
> Random Mappings

- mappings/net/minecraft/util/math/noise/OctaveSimplexNoiseSampler.mapping
- mappings/net/minecraft/world/biome/Biome.mapping
- mappings/net/minecraft/world/biome/ForestBiome.mapping
- mappings/net/minecraft/world/biome/JungleBiome.mapping
- mappings/net/minecraft/world/biome/MountainsBiome.mapping
- mappings/net/minecraft/world/biome/PlainsBiome.mapping
- mappings/net/minecraft/world/biome/SavannaBiome.mapping
- mappings/net/minecraft/world/biome/SnowyTundraBiome.mapping
- mappings/net/minecraft/world/biome/SwampBiome.mapping
- mappings/net/minecraft/world/biome/TaigaBiome.mapping
- mappings/net/minecraft/world/biome/TallBirchForestBiome.mapping
- mappings/net/minecraft/world/gen/feature/BirchTreeFeature.mapping
- mappings/net/minecraft/world/gen/feature/DeadBushFeature.mapping
- mappings/net/minecraft/world/gen/feature/GlowstoneBlobFeature2.mapping
- mappings/net/minecraft/world/gen/feature/JungleMelonFeature.mapping
- mappings/net/minecraft/world/gen/feature/PineTreeFeature.mapping
- mappings/net/minecraft/world/gen/feature/SpruceTreeFeature.mapping
- mappings/net/minecraft/world/gen/feature/SwampTreeFeature.mapping
Not sure about GlowstoneBlobFeature2
> Biomes and Features

- build.gradle
Opening a pull request so we can make sure this build has no unintended side effects.
> Remove spurious block, fixes #119

- mappings/net/minecraft/client/BlockStateMapper.mapping
- mappings/net/minecraft/client/render/block/BlockModelShapes.mapping
- mappings/net/minecraft/client/render/model/BakedModel.mapping
- mappings/net/minecraft/client/render/model/ModelLoader.mapping
- mappings/net/minecraft/client/render/model/TexturedBakedQuad.mapping
- mappings/net/minecraft/client/render/model/WeightedBakedModel.mapping
- mappings/net/minecraft/client/render/model/class_1073.mapping
- mappings/net/minecraft/client/render/model/json/BlockModel.mapping
- mappings/net/minecraft/client/render/model/json/ItemModelGenerator.mapping
- mappings/net/minecraft/client/render/model/json/ModelElement.mapping
- mappings/net/minecraft/client/render/model/json/ModelElementFace.mapping
- mappings/net/minecraft/client/render/model/json/ModelElementTexture.mapping
- mappings/net/minecraft/client/render/model/json/ModelRotation.mapping
- mappings/net/minecraft/client/render/model/json/ModelTransformation.mapping
- mappings/net/minecraft/client/render/model/json/ModelVariantMap.mapping
- mappings/net/minecraft/client/render/model/json/Transformation.mapping
> Models and Json mappings 

- README.md
- build.gradle
- yarn
- yarn.bat
- yarn_1.10.2
- yarn_1.11.2
- yarn_1.12.2
- yarn_1.13.2
- yarn_1.3.2
- yarn_1.4.7
- yarn_1.5.2
- yarn_1.6.4
- yarn_1.7.10
- yarn_1.8.9
- yarn_1.8.9.bat
- yarn_1.9.4
Implements a yarn version launcher for both Windows and Linux
> Yarn version launcher

- mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
- mappings/net/minecraft/block/entity/DispenserBlockEntity.mapping
- mappings/net/minecraft/block/entity/EnderChestBlockEntity.mapping
- mappings/net/minecraft/block/entity/FlowerPotBlockEntity.mapping
- mappings/net/minecraft/block/entity/FurnaceBlockEntity.mapping
- mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
- mappings/net/minecraft/block/entity/NoteBlockBlockEntity.mapping
- mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
- mappings/net/minecraft/block/entity/SignBlockEntity.mapping
- mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
- mappings/net/minecraft/client/model/ModelPart.mapping
- mappings/net/minecraft/client/network/PlayerListEntry.mapping
A small contribution to the 1.8.9 mappings.
(Not the same as the pr I submitted earlier)
> Some 1.8.9 mappings

- mappings/net/minecraft/class_469.mapping
- mappings/net/minecraft/class_481.mapping
- mappings/net/minecraft/client/MinecraftClient.mapping
- mappings/net/minecraft/client/util/OperatingSystem.mapping
- mappings/net/minecraft/client/util/OperationSystem.mapping
- mappings/net/minecraft/network/Connection.mapping
- mappings/net/minecraft/network/DisconnectThread.mapping
- mappings/net/minecraft/network/IntegratedConnection.mapping
- mappings/net/minecraft/network/OutboundConnection.mapping
- mappings/net/minecraft/network/Packet.mapping
- mappings/net/minecraft/network/PacketReaderThread.mapping
- mappings/net/minecraft/network/PacketWriterThread.mapping
- mappings/net/minecraft/network/ShutdownThread.mapping
- mappings/net/minecraft/server/BanEntry.mapping
- mappings/net/minecraft/server/BannedIpList.mapping
- mappings/net/minecraft/server/PlayerManager.mapping
- mappings/net/minecraft/util/log/LogManagerImpl.mapping
- mappings/net/minecraft/util/logging/LogFormatter.mapping
- mappings/net/minecraft/util/logging/LogManager.mapping
- mappings/net/minecraft/util/logging/LogManagerImpl.mapping
Probably some dodgy mapping names but everything should hopefully be correct
> 1.6.4 Networking: Connection edition

- mappings/net/minecraft/text/ChatMessage.mapping
- mappings/net/minecraft/text/ChatMessageSerializer.mapping
- mappings/net/minecraft/text/class_1687.mapping
- mappings/net/minecraft/text/class_1688.mapping
Hello, my first humble pull request here. I did these mappings for 1.6.4. I used https://gist.github.com/Dinnerbone/5631634 that describes the chat system as reference to understand the structure of messages.
> add ChatMessage mappings

- .github/workflows/build.yml
- .github/workflows/publish.yml
- There's no reason to test every single minor version every single time. It only causes issues with testing submitted changes.
- Publishing changes from every branch can have terrible consequences!
> Uncrazy-fy the build Workflow

- build.gradle
- test-mod/build.gradle
- test-mod/gradle.properties
~~Haven't tested that the build number works so don't merge yet~~
> Changed group to legacyfabric and updated build numbering

- mappings/net/minecraft/server/command/FunctionCommand.mapping
- mappings/net/minecraft/server/command/LocateCommand.mapping
- mappings/net/minecraft/server/command/RecipeCommand.mapping
- mappings/net/minecraft/server/command/ReloadCommand.mapping
- mappings/net/minecraft/server/command/TpCommand.mapping
- mappings/net/minecraft/server/rcon/RconClient.mapping
- mappings/net/minecraft/server/rcon/RconServer.mapping
contains command mappings
and argument naming in RconClient/RconServer
> command mappings, some Rcon{Server,Client} mappings

- mappings/net/minecraft/class_3012.mapping
- mappings/net/minecraft/predicate/block/BlockMaterialPredicate.mapping
- mappings/net/minecraft/predicate/block/BlockPredicate.mapping
- mappings/net/minecraft/predicate/block/BlockStatePredicate.mapping
this moves the BlockStatePredicate from block to predicate.block
> Net.minecraft.predicate

- mappings/net/minecraft/loot/class_2780.mapping
- mappings/net/minecraft/loot/class_2787.mapping
it might be a good idea to look thought all classes at once and do that to all of them then...
> name the logger LOGGER

- mappings/net/minecraft/enchantment/AquaAffinityEnchantment.mapping
- mappings/net/minecraft/enchantment/BindingCurseEnchantment.mapping
- mappings/net/minecraft/enchantment/DamageEnchantment.mapping
- mappings/net/minecraft/enchantment/DepthStriderEnchantment.mapping
- mappings/net/minecraft/enchantment/EfficiencyEnchantment.mapping
- mappings/net/minecraft/enchantment/FireAspectEnchantment.mapping
- mappings/net/minecraft/enchantment/FlameEnchantment.mapping
- mappings/net/minecraft/enchantment/FrostWalkerEnchantment.mapping
- mappings/net/minecraft/enchantment/InfinityEnchantment.mapping
- mappings/net/minecraft/enchantment/KnockbackEnchantment.mapping
- mappings/net/minecraft/enchantment/MendingEnchantment.mapping
- mappings/net/minecraft/enchantment/PowerEnchantment.mapping
- mappings/net/minecraft/enchantment/PunchEnchantment.mapping
- mappings/net/minecraft/enchantment/RespirationEnchantment.mapping
- mappings/net/minecraft/enchantment/SilkTouchEnchantment.mapping
- mappings/net/minecraft/enchantment/SweepingEnchantment.mapping
- mappings/net/minecraft/enchantment/ThornsEnchantment.mapping
- mappings/net/minecraft/enchantment/UnbreakingEnchantment.mapping
- mappings/net/minecraft/enchantment/VanishingCurseEnchantment.mapping
the first parameter of super is the rarity, the second the slots it can be used in/on
> name the parameters of all constructors of .enchantment

- mappings/net/minecraft/block/entity/ShulkerBoxBlockEntity.mapping
- mappings/net/minecraft/block/entity/class_2737.mapping
(setName is based on the field name it sets)
> map block.entity.ShulkerBoxBlockEntity.getColor() and setName

- mappings/net/minecraft/server/command/RecipeCommand.mapping
- mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
- mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
move the RecipeCommand from .server to .server.command...
> map some .server stuff

- mappings/net/minecraft/world/World.mapping
- mappings/net/minecraft/world/WorldEventListener.mapping
- mappings/net/minecraft/world/biome/BiomeDecorator.mapping
- mappings/net/minecraft/world/biome/MesaBiome.mapping
- mappings/net/minecraft/world/chunk/Chunk.mapping
- mappings/net/minecraft/world/chunk/ChunkBlockStateStorage.mapping
- mappings/net/minecraft/world/chunk/ChunkStorage.mapping
- mappings/net/minecraft/world/chunk/EndChunkGenerator.mapping
- mappings/net/minecraft/world/chunk/RegionIo.mapping
- mappings/net/minecraft/world/chunk/ServerChunkProvider.mapping
- mappings/net/minecraft/world/chunk/SurfaceChunkGenerator.mapping
- mappings/net/minecraft/world/dimension/Dimension.mapping
- mappings/net/minecraft/world/dimension/TheEndDimension.mapping
- mappings/net/minecraft/world/gen/CustomizedWorldProperties.mapping
- mappings/net/minecraft/world/gen/feature/EndGatewayFeature.mapping
- mappings/net/minecraft/world/gen/feature/NetherSpringFeature.mapping
- mappings/net/minecraft/world/gen/feature/SpringFeature.mapping
- mappings/net/minecraft/world/gen/feature/class_2753.mapping
- mappings/net/minecraft/world/level/LevelProperties.mapping
NetherrackFeature and StoneFeature are called NetherSpringFeature and SpringFeature, as they generate the one source block liquid thingys
> do some mapping in world

- mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
- mappings/net/minecraft/client/MinecraftClient.mapping
- mappings/net/minecraft/client/option/GameOption.mapping
- mappings/net/minecraft/client/option/GameOptions.mapping
- mappings/net/minecraft/client/option/KeyBinding.mapping
- mappings/net/minecraft/client/option/ServerList.mapping
I had a fork (because I wanted to take inspiration from MCP) but I realise it's probably best just to contribute (turns out my changes weren't really MCP-inspired).
I'm sure there were more upstream changes but these are just the ones I noticed.
> A few tweaks

- mappings/net/minecraft/scoreboard/AbstractTeam.mapping
- mappings/net/minecraft/scoreboard/Team.mapping
rename field/getter to match setter name `setNameTagVisibilityRule`
> Fix AbstractTeam#getNameTagVisibilityRule
